// ignore_for_file: avoid_renaming_method_parameters,duplicate_import, unused_import, unnecessary_null_comparison, unnecessary_non_null_assertion

/// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'dart:convert';
import 'package:sunny_sdk_core/api_exports.dart';

import 'package:sunny_sdk_core/sunny_sdk_core.dart';

import '../scheduling.dart';


///
/// DO NOT MODIFY
///
/// GENERATED API OPERATIONS
///
abstract class IMeetingApi extends Repository<IMeeting> /* sunny:scheduling:schema:meeting:0.0.1@mverse*/{

  @override
  MSchemaRef get mtype => MeetingRef;

  Future<IMeeting> create(IMeeting meeting,);
    
  Future<DeleteResponse> delete(String id,);
    
  Future<IMeetingList> list({ double? limit,  double? offset });
    
  Future<IMeeting> load(String id,);
    
  Future<ChangeResult> update(String id, IMeeting meeting,);
    
}