// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../fact_schemas_ext.dart';



class IFactDuration extends MLiteral<String> {
  static late IFactDuration? Function(dynamic any) fromJson;
  static late IFactDurationValues values;
  static IFactDuration get permanent_ => values.permanent_;
  static IFactDuration get expiring_ => values.expiring_;
  static IFactDuration get event_ => values.event_;
  static IFactDuration get manual_ => values.manual_;
  static IFactDuration get reverse_ => values.reverse_;

  final bool isKnown;
  @protected
  const IFactDuration.internal(String value): isKnown = true, super(value);
  const IFactDuration.unknown(String value): isKnown = false, super(value);
}

class IFactDurationValues extends ListDelegateMixin<IFactDuration> {
    final IFactDuration permanent_;
    final IFactDuration expiring_;
    final IFactDuration event_;
    final IFactDuration manual_;
    final IFactDuration reverse_;

  @override
  final List<IFactDuration> delegate;

  IFactDurationValues(this.permanent_,
      this.expiring_,
      this.event_,
      this.manual_,
      this.reverse_) : delegate = List.unmodifiable([permanent_,expiring_,event_,manual_,reverse_]);
}
