// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../fact_schemas_ext.dart';



class IFactTense extends MLiteral<String> {
  static late IFactTense? Function(dynamic any) fromJson;
  static late IFactTenseValues values;
  static IFactTense get past_ => values.past_;
  static IFactTense get present_ => values.present_;
  static IFactTense get future_ => values.future_;

  final bool isKnown;
  @protected
  const IFactTense.internal(String value): isKnown = true, super(value);
  const IFactTense.unknown(String value): isKnown = false, super(value);
}

class IFactTenseValues extends ListDelegateMixin<IFactTense> {
    final IFactTense past_;
    final IFactTense present_;
    final IFactTense future_;

  @override
  final List<IFactTense> delegate;

  IFactTenseValues(this.past_,
      this.present_,
      this.future_) : delegate = List.unmodifiable([past_,present_,future_]);
}
