// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../fact_schemas_ext.dart';



class IFactRecurrence extends MLiteral<String> {
  static late IFactRecurrence? Function(dynamic any) fromJson;
  static late IFactRecurrenceValues values;
  static IFactRecurrence get yearly_ => values.yearly_;
  static IFactRecurrence get monthly_ => values.monthly_;
  static IFactRecurrence get unknown_ => values.unknown_;

  final bool isKnown;
  @protected
  const IFactRecurrence.internal(String value): isKnown = true, super(value);
  const IFactRecurrence.unknown(String value): isKnown = false, super(value);
}

class IFactRecurrenceValues extends ListDelegateMixin<IFactRecurrence> {
    final IFactRecurrence yearly_;
    final IFactRecurrence monthly_;
    final IFactRecurrence unknown_;

  @override
  final List<IFactRecurrence> delegate;

  IFactRecurrenceValues(this.yearly_,
      this.monthly_,
      this.unknown_) : delegate = List.unmodifiable([yearly_,monthly_,unknown_]);
}
