// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../fact_schemas_ext.dart';



class IFactAgent extends MLiteral<String> {
  static late IFactAgent? Function(dynamic any) fromJson;
  static late IFactAgentValues values;
  static IFactAgent get neither_ => values.neither_;
  static IFactAgent get both_ => values.both_;
  static IFactAgent get user_ => values.user_;
  static IFactAgent get subject_ => values.subject_;

  final bool isKnown;
  @protected
  const IFactAgent.internal(String value): isKnown = true, super(value);
  const IFactAgent.unknown(String value): isKnown = false, super(value);
}

class IFactAgentValues extends ListDelegateMixin<IFactAgent> {
    final IFactAgent neither_;
    final IFactAgent both_;
    final IFactAgent user_;
    final IFactAgent subject_;

  @override
  final List<IFactAgent> delegate;

  IFactAgentValues(this.neither_,
      this.both_,
      this.user_,
      this.subject_) : delegate = List.unmodifiable([neither_,both_,user_,subject_]);
}
