// ignore_for_file: avoid_renaming_method_parameters,duplicate_import, unused_import, unnecessary_null_comparison, unnecessary_non_null_assertion

/// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'dart:convert';
import 'package:sunny_sdk_core/api_exports.dart';

import 'package:sunny_sdk_core/sunny_sdk_core.dart';
import '../model/account_content_template.dart';
import '../model/account_content_template_list.dart';

import '../waypoints.dart';


///
/// DO NOT MODIFY
///
/// GENERATED API OPERATIONS
///
abstract class IAccountContentTemplateApi extends Repository<IAccountContentTemplate> /* sunny:content:schema:accountContentTemplate:0.0.1@mverse*/{

  @override
  MSchemaRef get mtype => AccountContentTemplateRef;

  Future<IAccountContentTemplate> create(IAccountContentTemplate accountContentTemplate,);
    
  Future<DeleteResponse> delete(String id,);
    
  Future<IAccountContentTemplateList> list({ double? limit,  double? offset });
    
  Future<IAccountContentTemplate> load(String id,);
    
  Future<ChangeResult> update(String id, IAccountContentTemplate accountContentTemplate,);
    
}