// ignore_for_file: avoid_renaming_method_parameters,duplicate_import, unused_import, unnecessary_null_comparison, unnecessary_non_null_assertion

/// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'dart:convert';
import 'package:meta/meta.dart';
import 'package:sunny_sdk_core/api_exports.dart';

import '../model/render_context.dart';
import '../model/template_render_results.dart';

import '../waypoints.dart';


///
/// DO NOT MODIFY
///
/// GENERATED API OPERATIONS
///
abstract class IContentApi extends Repository<IContent> /* sunny:content:schema:content:0.0.1@ephemeral*/{

  @override
  MSchemaRef get mtype => ContentRef;

  Future<IRenderContext> buildRenderContext(IBuildRenderContextRequest buildRenderContextRequest,);
    
  Future<ITemplateRenderResults> renderTemplates(IRenderTemplatesRequest renderTemplatesRequest,);
    
}