// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../scheduling_ext.dart';

import '../model/attendee.dart';
import 'package:sunny_service_stubs/models/waypoints/model/flow_frame.dart';
import 'package:sunny_service_stubs/models/waypoints/model/flow_thread.dart';
import 'package:sunny_service_stubs/models/waypoints/model/thread_status.dart';


abstract class IAttendeeFlowThread
  implements IFlowThread {

  static late _AttendeeFlowThreadConstructor of;
  static late _AttendeeFlowThreadFromJson fromJson;

  /// Property getter and setter for attendee: 
  IAttendee? get attendee;
  set attendee(IAttendee? attendee);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IAttendeeFlowThread clone();

  @override
  Set<String> get mfields => AttendeeFlowThreadFields.values;

}

class AttendeeFlowThreadFields {
  static const parent = "parent";
  static const graphId = "graphId";
  static const started = "started";
  static const completed = "completed";
  static const status = "status";
  static const isActive = "isActive";
  static const subjects = "subjects";
  static const state = "state";
  static const frames = "frames";
  static const attendee = "attendee";
  static const Set<String> values = {
    parent, graphId, started, completed, status, isActive, subjects, state, frames, attendee
  };
}

class AttendeeFlowThreadPaths {
  static const JsonPath<IFlowThread> parent = JsonPath.internal(["parent"], "/parent");
  static const JsonPath<String> graphId = JsonPath.internal(["graphId"], "/graphId");
  static const JsonPath<DateTime> started = JsonPath.internal(["started"], "/started");
  static const JsonPath<DateTime> completed = JsonPath.internal(["completed"], "/completed");
  static const JsonPath<IThreadStatus> status = JsonPath.internal(["status"], "/status");
  static const JsonPath<bool> isActive = JsonPath.internal(["isActive"], "/isActive");
  static const JsonPath<Map<String, MEntity>> subjects = JsonPath.internal(["subjects"], "/subjects");
  static const JsonPath<MModel> state = JsonPath.internal(["state"], "/state");
  static const JsonPath<List<IFlowFrame>> frames = JsonPath.internal(["frames"], "/frames");
  static const JsonPath<IAttendee> attendee = JsonPath.internal(["attendee"], "/attendee");
  static final Set<JsonPath> values = {
    parent, graphId, started, completed, status, isActive, subjects, state, frames, attendee
  };
}


const AttendeeFlowThreadRef = MSchemaRef("sunny", "meetingFlow", "attendeeFlowThread", "0.0.1", "mverse");

typedef _AttendeeFlowThreadConstructor = IAttendeeFlowThread Function({   IFlowThread? parent, 
  required String? graphId, 
  required DateTime? started, 
  DateTime? completed, 
  required IThreadStatus? status, 
  required bool? isActive, 
  required Map<String, MEntity>? subjects, 
  MModel? state, 
  required List<IFlowFrame>? frames, 
  required IAttendee? attendee
 });
typedef _AttendeeFlowThreadFromJson = IAttendeeFlowThread Function(dynamic any);