// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../scheduling_ext.dart';

import '../model/attendee_flow_thread.dart';


abstract class IAttendeeFlowThreadList
  implements MModel, MModelList<IAttendeeFlowThread> {

  static late _AttendeeFlowThreadListConstructor of;
  static late _AttendeeFlowThreadListFromJson fromJson;

  /// Property getter and setter for count: 
  int? get count;
  set count(int? count);


  /// Property getter and setter for data: 
  List<IAttendeeFlowThread>? get data;
  set data(List<IAttendeeFlowThread>? data);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IAttendeeFlowThreadList clone();

  @override
  Set<String> get mfields => AttendeeFlowThreadListFields.values;

}

class AttendeeFlowThreadListFields {
  static const count = "count";
  static const data = "data";
  static const Set<String> values = {
    count, data
  };
}

class AttendeeFlowThreadListPaths {
  static const JsonPath<int> count = JsonPath.internal(["count"], "/count");
  static const JsonPath<List<IAttendeeFlowThread>> data = JsonPath.internal(["data"], "/data");
  static final Set<JsonPath> values = {
    count, data
  };
}


const AttendeeFlowThreadListRef = MSchemaRef("sunny", "meetingFlow", "attendeeFlowThreadList", "0.0.1", "ephemeral");

typedef _AttendeeFlowThreadListConstructor = IAttendeeFlowThreadList Function({   int? count, 
  List<IAttendeeFlowThread>? data
 });
typedef _AttendeeFlowThreadListFromJson = IAttendeeFlowThreadList Function(dynamic any);