// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';

import '../../contact_v2/model/physical_location.dart';


abstract class IInPersonInfo implements MModel {
  /// Property getter and setter for location: 
  IPhysicalLocation? get location;
  set location(IPhysicalLocation? location);

  /// Property getter and setter for howToPrepare: 
  String? get howToPrepare;
  set howToPrepare(String? howToPrepare);

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IInPersonInfo clone();

  @override
  Set<String> get mfields => InPersonInfoFields.values;

}

class InPersonInfoFields {
  
  static const location = "location";
  static const howToPrepare = "howToPrepare";
  static const Set<String> values = {
    location, howToPrepare
  };
}

class InPersonInfoPaths {
  
  static const JsonPath<IPhysicalLocation> location = JsonPath.internal(["location"], "/location");
  static const JsonPath<String> howToPrepare = JsonPath.internal(["howToPrepare"], "/howToPrepare");
  static final Set<JsonPath> values = {
    location, howToPrepare
  };
}


const InPersonInfoRef = MSchemaRef("sunny", "scheduling", "inPersonInfo", "0.0.1", "ephemeral");