// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../scheduling_ext.dart';

import '../model/meeting_flow_thread.dart';


abstract class IMeetingFlowThreadList
  implements MModel, MModelList<IMeetingFlowThread> {

  static late _MeetingFlowThreadListConstructor of;
  static late _MeetingFlowThreadListFromJson fromJson;

  /// Property getter and setter for count: 
  int? get count;
  set count(int? count);


  /// Property getter and setter for data: 
  List<IMeetingFlowThread>? get data;
  set data(List<IMeetingFlowThread>? data);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IMeetingFlowThreadList clone();

  @override
  Set<String> get mfields => MeetingFlowThreadListFields.values;

}

class MeetingFlowThreadListFields {
  static const count = "count";
  static const data = "data";
  static const Set<String> values = {
    count, data
  };
}

class MeetingFlowThreadListPaths {
  static const JsonPath<int> count = JsonPath.internal(["count"], "/count");
  static const JsonPath<List<IMeetingFlowThread>> data = JsonPath.internal(["data"], "/data");
  static final Set<JsonPath> values = {
    count, data
  };
}


const MeetingFlowThreadListRef = MSchemaRef("sunny", "meetingFlow", "meetingFlowThreadList", "0.0.1", "ephemeral");

typedef _MeetingFlowThreadListConstructor = IMeetingFlowThreadList Function({   int? count, 
  List<IMeetingFlowThread>? data
 });
typedef _MeetingFlowThreadListFromJson = IMeetingFlowThreadList Function(dynamic any);