// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../scheduling_ext.dart';



abstract class IMeetingReminderTaskInfo
  implements MModel {

  static late _MeetingReminderTaskInfoConstructor of;
  static late _MeetingReminderTaskInfoFromJson fromJson;

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IMeetingReminderTaskInfo clone();

}


const MeetingReminderTaskInfoRef = MSchemaRef("sunny", "meetingFlow", "meetingReminderTaskInfo", "0.0.1", "ephemeral");

typedef _MeetingReminderTaskInfoConstructor = IMeetingReminderTaskInfo Function();
typedef _MeetingReminderTaskInfoFromJson = IMeetingReminderTaskInfo Function(dynamic any);