name: sunny_service_stubs
version: 0.4.0+1
description: A new Flutter package project.
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies: 
  timezone: ^0.7.0
  meta: ^1.3.0
  sunny_data: ^1.0.0+1
  logging: ^1.0.1
  intl: ^0.17.0
  info_x: ^0.6.0+1
  pfile: ^2.1.0+2
  sunny_dart: ^0.10.0+1
  flexidate: ^0.6.0+2
  equatable: ^2.0.0
  dartxx: ^0.5.0+2
  collection_diff: ^2.0.3+6
  sunny_sdk_core: ^2.0.0+7
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
