name: sunny_service_stubs
version: 0.5.1
description: Stubs for working with sunny services
repository: https://github.com/ericmartineau/sunny_services.git
environment: 
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies: 
  equatable: ^2.0.5
  logging: ^1.1.1
  meta: ^1.9.0
  intl: ^0.18.0
  timezone: ^0.9.1
  collection_diff: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/collection_diff
  flexidate: 
    path: /Users/ericm/reliveit/checkout/ericmartineau/flexidate
  info_x: 
    path: /Users/ericm/reliveit/checkout/ericmartineau/info_x
  pfile: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/pfile
  sunny_data: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/sunny_data
  sunny_sdk_core: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/sunny_sdk_core
  dartxx: 
    path: /Users/ericm/reliveit/checkout/ericmartineau/dartxx
  sunny_dart: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/sunny_dart
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
