name: sunny_service_stubs
version: 0.1.1-nullsafety.11
description: A new Flutter package project.
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies: 
  timezone: ^0.7.0-nullsafety.0
  meta: ^1.3.0
  sunny_data: ^1.0.0-nullsafety.2
  logging: ^1.0.0
  intl: ^0.17.0
  pfile: ^2.0.1-nullsafety.3
  sunny_dart: ^0.8.3+2
  flexidate: ^0.4.5-nullsafety.2
  equatable: ^2.0.0
  dartxx: ^0.4.5-nullsafety.6
  collection_diff: ^2.0.3+5
  sunny_sdk_core: ^2.0.0-nullsafe.17
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
