name: sunny_service_stubs
version: 0.5.1
description: Stubs for working with sunny services
repository: https://github.com/ericmartineau/sunny_services.git
environment: 
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies: 
  equatable: ^2.0.5
  logging: ^1.0.2
  meta: ^1.8.0
  intl: ^0.17.0
  timezone: ^0.9.0
  collection_diff: 
    git: 
      url: git@github.com:SunnyApp/collection_diff
      ref: trippi_app
  info_x: 
    git: 
      url: git@github.com:ericmartineau/info_x
      ref: trippi_app
  sunny_data: 
    git: 
      url: git@github.com:TrippiApp/sunny_data.git
      ref: trippi_app
  flexidate: 
    git: 
      url: git@github.com:TrippiApp/flexidate
      ref: trippi_app
  pfile: 
    git: 
      url: git@github.com:SunnyApp/pfile
      ref: trippi_app
  sunny_sdk_core: 
    git: 
      url: git@github.com:SunnyApp/sunny_sdk_core.git
      ref: trippi_app
  dartxx: 
    git: 
      url: git@github.com:ericmartineau/dartxx.git
      ref: trippi_app
  sunny_dart: 
    git: 
      url: git@github.com:SunnyApp/sunny_dart
      ref: trippi_app
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
