name: sunny_service_stubs
version: 0.0.1-nullsafety.3
description: A new Flutter package project.
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies: 
  timezone: ^0.7.0-nullsafety.0
  sunny_dart: ^0.8.0+7
  flexidate: ^0.4.5-nullsafety.2
  equatable: ^2.0.0-nullsafety.0
  dartxx: ^0.4.5-nullsafety.2
  collection_diff: ^2.0.3+5
  sunny_sdk_core: ^2.0.0-nullsafe.14
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
