// ignore_for_file: avoid_renaming_method_parameters,duplicate_import, unused_import, unnecessary_null_comparison, unnecessary_non_null_assertion

/// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'dart:convert';
import 'package:meta/meta.dart';
import 'package:sunny_sdk_core/api_exports.dart';

import 'package:sunny_sdk_core/sunny_sdk_core.dart';
import '../model/truman_health_info.dart';
import '../model/truman_health_info_list.dart';

import '../truman.dart';


///
/// DO NOT MODIFY
///
/// GENERATED API OPERATIONS
///
abstract class ITrumanHealthInfoApi extends Repository<ITrumanHealthInfo> /* truman:sunny:schema:trumanHealthInfo:0.0.1@mverse*/{

  @override
  MSchemaRef get mtype => TrumanHealthInfoRef;

  Future<ITrumanHealthInfo> create(ITrumanHealthInfo trumanHealthInfo,);
    
  Future<DeleteResponse> delete(String id,);
    
  Future<ITrumanHealthInfoList> list({ double? limit,  double? offset });
    
  Future<ITrumanHealthInfo> load(String id,);
    
  Future<ChangeResult> update(String id, ITrumanHealthInfo trumanHealthInfo,);
    
}