// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../contact_v2_ext.dart';

import '../model/contact.dart';


abstract class IContactList
  implements MModel, MModelList<IContact> {

  static late _ContactListConstructor of;
  static late _ContactListFromJson fromJson;

  /// Property getter and setter for count: 
  int? get count;
  set count(int? count);


  /// Property getter and setter for data: 
  List<IContact>? get data;
  set data(List<IContact>? data);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IContactList clone();

  @override
  Set<String> get mfields => ContactListFields.values;

}

class ContactListFields {
  static const count = "count";
  static const data = "data";
  static const Set<String> values = {
    count, data
  };
}

class ContactListPaths {
  static const JsonPath<int> count = JsonPath.internal(["count"], "/count");
  static const JsonPath<List<IContact>> data = JsonPath.internal(["data"], "/data");
  static final Set<JsonPath> values = {
    count, data
  };
}


const ContactListRef = MSchemaRef("mverse", "contact", "contactList", "0.0.1", "ephemeral");

typedef _ContactListConstructor = IContactList Function({   int? count, 
  List<IContact>? data
 });
typedef _ContactListFromJson = IContactList Function(dynamic any);