// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';



abstract class ITask implements MEntity {
  /// Property getter and setter for contact: 
  String? get contact;
  

  /// Property getter and setter for title: 
  String? get title;
  

  /// Property getter and setter for description: 
  String? get description;
  

  /// Property getter and setter for dueDate: 
  DateTime? get dueDate;
  

  /// Property getter and setter for completeDate: 
  DateTime? get completeDate;
  

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  ITask clone();

  @override
  Set<String> get mfields => TaskFields.values;

}

class TaskFields {
  
  static const contact = "contact";
  static const title = "title";
  static const description = "description";
  static const dueDate = "dueDate";
  static const completeDate = "completeDate";
  static const Set<String> values = {
    contact, title, description, dueDate, completeDate
  };
}

class TaskPaths {
  
  static const JsonPath<String> contact = JsonPath.internal(["contact"], "/contact");
  static const JsonPath<String> title = JsonPath.internal(["title"], "/title");
  static const JsonPath<String> description = JsonPath.internal(["description"], "/description");
  static const JsonPath<DateTime> dueDate = JsonPath.internal(["dueDate"], "/dueDate");
  static const JsonPath<DateTime> completeDate = JsonPath.internal(["completeDate"], "/completeDate");
  static final Set<JsonPath> values = {
    contact, title, description, dueDate, completeDate
  };
}


const TaskRef = MSchemaRef("mverse", "contact", "task", "0.0.1", "abstract");