// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../push_message_ext.dart';



class IPushDisplayType extends MLiteral<String> {
  static late IPushDisplayType? Function(dynamic any) fromJson;
  static late IPushDisplayTypeValues values;
  static IPushDisplayType get bottomSheet_ => values.bottomSheet_;
  static IPushDisplayType get modal_ => values.modal_;
  static IPushDisplayType get page_ => values.page_;

  final bool isKnown;
  @protected
  const IPushDisplayType.internal(String value): isKnown = true, super(value);
  const IPushDisplayType.unknown(String value): isKnown = false, super(value);
}

class IPushDisplayTypeValues extends ListDelegateMixin<IPushDisplayType> {
    final IPushDisplayType bottomSheet_;
    final IPushDisplayType modal_;
    final IPushDisplayType page_;

  @override
  final List<IPushDisplayType> delegate;

  IPushDisplayTypeValues(this.bottomSheet_,
      this.modal_,
      this.page_) : delegate = List.unmodifiable([bottomSheet_,modal_,page_]);
}
