// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../waypoints_ext.dart';

import 'package:sunny_sdk_core/sunny_sdk_core.dart';


abstract class IChangeGroupMembershipsRequest
  implements MModel {

  static late _ChangeGroupMembershipsRequestConstructor of;
  static late _ChangeGroupMembershipsRequestFromJson fromJson;

  /// Property getter and setter for flowThreadId: 
  RecordKey? get flowThreadId;
  set flowThreadId(RecordKey? flowThreadId);


  /// Property getter and setter for removes: 
  List<String>? get removes;
  set removes(List<String>? removes);


  /// Property getter and setter for adds: 
  List<String>? get adds;
  set adds(List<String>? adds);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IChangeGroupMembershipsRequest clone();

  @override
  Set<String> get mfields => ChangeGroupMembershipsRequestFields.values;

}

class ChangeGroupMembershipsRequestFields {
  static const flowThreadId = "flowThreadId";
  static const removes = "removes";
  static const adds = "adds";
  static const Set<String> values = {
    flowThreadId, removes, adds
  };
}

class ChangeGroupMembershipsRequestPaths {
  static const JsonPath<RecordKey> flowThreadId = JsonPath.internal(["flowThreadId"], "/flowThreadId");
  static const JsonPath<List<String>> removes = JsonPath.internal(["removes"], "/removes");
  static const JsonPath<List<String>> adds = JsonPath.internal(["adds"], "/adds");
  static final Set<JsonPath> values = {
    flowThreadId, removes, adds
  };
}


const ChangeGroupMembershipsRequestRef = MSchemaRef("sunny", "groupFlow", "changeGroupMembershipsRequest", "0.0.1", "ephemeral");

typedef _ChangeGroupMembershipsRequestConstructor = IChangeGroupMembershipsRequest Function({   required RecordKey? flowThreadId, 
  required List<String>? removes, 
  required List<String>? adds
 });
typedef _ChangeGroupMembershipsRequestFromJson = IChangeGroupMembershipsRequest Function(dynamic any);