// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../waypoints_ext.dart';

import '../model/expression.dart';
import '../model/flow_query.dart';
import 'package:sunny_dart/json.dart';


abstract class IFactFlowQuery
  implements IFlowQuery {

  static late _FactFlowQueryConstructor of;
  static late _FactFlowQueryFromJson fromJson;

  /// Property getter and setter for factRef: 
  MSchemaRef? get factRef;
  set factRef(MSchemaRef? factRef);


  /// Property getter and setter for factPath: 
  JsonPath? get factPath;
  set factPath(JsonPath? factPath);


  /// Property getter and setter for factExpression: 
  IExpression? get factExpression;
  set factExpression(IExpression? factExpression);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IFactFlowQuery clone();

  @override
  Set<String> get mfields => FactFlowQueryFields.values;

}

class FactFlowQueryFields {
  static const factRef = "factRef";
  static const factPath = "factPath";
  static const factExpression = "factExpression";
  static const Set<String> values = {
    factRef, factPath, factExpression
  };
}

class FactFlowQueryPaths {
  static const JsonPath<MSchemaRef> factRef = JsonPath.internal(["factRef"], "/factRef");
  static const JsonPath<JsonPath> factPath = JsonPath.internal(["factPath"], "/factPath");
  static const JsonPath<IExpression> factExpression = JsonPath.internal(["factExpression"], "/factExpression");
  static final Set<JsonPath> values = {
    factRef, factPath, factExpression
  };
}


const FactFlowQueryRef = MSchemaRef("sunny", "waypoints", "factFlowQuery", "0.0.1", "ephemeral");

typedef _FactFlowQueryConstructor = IFactFlowQuery Function({   required MSchemaRef? factRef, 
  required JsonPath? factPath, 
  required IExpression? factExpression
 });
typedef _FactFlowQueryFromJson = IFactFlowQuery Function(dynamic any);