// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';

import '../model/contact_thread_state.dart';
import 'package:sunny_sdk_core/sunny_sdk_core.dart';


abstract class IFactThreadState implements IContactThreadState {
  /// Property getter and setter for factType: 
  MSchemaRef? get factType;
  set factType(MSchemaRef? factType);

  /// Property getter and setter for factKey: 
  RecordKey? get factKey;
  set factKey(RecordKey? factKey);

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IFactThreadState clone();

  @override
  Set<String> get mfields => FactThreadStateFields.values;

}

class FactThreadStateFields {
  
  static const contactId = "contactId";
  static const factType = "factType";
  static const factKey = "factKey";
  static const Set<String> values = {
    contactId, factType, factKey
  };
}

class FactThreadStatePaths {
  
  static const JsonPath<String> contactId = JsonPath.internal(["contactId"], "/contactId");
  static const JsonPath<MSchemaRef> factType = JsonPath.internal(["factType"], "/factType");
  static const JsonPath<RecordKey> factKey = JsonPath.internal(["factKey"], "/factKey");
  static final Set<JsonPath> values = {
    contactId, factType, factKey
  };
}


const FactThreadStateRef = MSchemaRef("sunny", "waypoints", "factThreadState", "0.0.1", "ephemeral");