// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../waypoints_ext.dart';

import '../model/flow_node.dart';


abstract class IFlowNodes
  implements MModel {

  static late _FlowNodesConstructor of;
  static late _FlowNodesFromJson fromJson;

  /// Property getter and setter for count: 
  int? get count;
  set count(int? count);


  /// Property getter and setter for data: 
  List<IFlowNode>? get data;
  set data(List<IFlowNode>? data);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IFlowNodes clone();

  @override
  Set<String> get mfields => FlowNodesFields.values;

}

class FlowNodesFields {
  static const count = "count";
  static const data = "data";
  static const Set<String> values = {
    count, data
  };
}

class FlowNodesPaths {
  static const JsonPath<int> count = JsonPath.internal(["count"], "/count");
  static const JsonPath<List<IFlowNode>> data = JsonPath.internal(["data"], "/data");
  static final Set<JsonPath> values = {
    count, data
  };
}


const FlowNodesRef = MSchemaRef("sunny", "waypointsBuilder", "flowNodes", "0.0.1", "ephemeral");

typedef _FlowNodesConstructor = IFlowNodes Function({   required int? count, 
  required List<IFlowNode>? data
 });
typedef _FlowNodesFromJson = IFlowNodes Function(dynamic any);