// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../waypoints_ext.dart';



class IFrameStatus extends MLiteral<String> {
  static late IFrameStatus? Function(dynamic any) fromJson;
  static late IFrameStatusValues values;
  static IFrameStatus get initialized_ => values.initialized_;
  static IFrameStatus get started_ => values.started_;
  static IFrameStatus get skipped_ => values.skipped_;
  static IFrameStatus get timedOut_ => values.timedOut_;
  static IFrameStatus get error_ => values.error_;
  static IFrameStatus get cancelled_ => values.cancelled_;
  static IFrameStatus get completed_ => values.completed_;

  final bool isKnown;
  @protected
  const IFrameStatus.internal(String value): isKnown = true, super(value);
  const IFrameStatus.unknown(String value): isKnown = false, super(value);
}

class IFrameStatusValues extends ListDelegateMixin<IFrameStatus> {
    final IFrameStatus initialized_;
    final IFrameStatus started_;
    final IFrameStatus skipped_;
    final IFrameStatus timedOut_;
    final IFrameStatus error_;
    final IFrameStatus cancelled_;
    final IFrameStatus completed_;

  @override
  final List<IFrameStatus> delegate;

  IFrameStatusValues(this.initialized_,
      this.started_,
      this.skipped_,
      this.timedOut_,
      this.error_,
      this.cancelled_,
      this.completed_) : delegate = List.unmodifiable([initialized_,started_,skipped_,timedOut_,error_,cancelled_,completed_]);
}
