// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../waypoints_ext.dart';

import '../model/content.dart';
import '../model/content_delivery.dart';
import 'package:sunny_sdk_core/sunny_sdk_core.dart';


abstract class IGiphyContent
  implements IContent {

  static late _GiphyContentConstructor of;
  static late _GiphyContentFromJson fromJson;

  /// Property getter and setter for giphyUrl: 
  String? get giphyUrl;
  set giphyUrl(String? giphyUrl);


  /// Property getter and setter for caption: 
  String? get caption;
  set caption(String? caption);


  /// Property getter and setter for text: 
  String? get text;
  set text(String? text);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IGiphyContent clone();

  @override
  Set<String> get mfields => GiphyContentFields.values;

}

class GiphyContentFields {
  static const dismissible = "dismissible";
  static const repeatsFor = "repeatsFor";
  static const showEvery = "showEvery";
  static const delivery = "delivery";
  static const durationUnit = "durationUnit";
  static const durationAmount = "durationAmount";
  static const delayUnit = "delayUnit";
  static const delayAmount = "delayAmount";
  static const giphyUrl = "giphyUrl";
  static const caption = "caption";
  static const text = "text";
  static const Set<String> values = {
    dismissible, repeatsFor, showEvery, delivery, durationUnit, durationAmount, delayUnit, delayAmount, giphyUrl, caption, text
  };
}

class GiphyContentPaths {
  static const JsonPath<bool> dismissible = JsonPath.internal(["dismissible"], "/dismissible");
  static const JsonPath<int> repeatsFor = JsonPath.internal(["repeatsFor"], "/repeatsFor");
  static const JsonPath<int> showEvery = JsonPath.internal(["showEvery"], "/showEvery");
  static const JsonPath<IContentDelivery> delivery = JsonPath.internal(["delivery"], "/delivery");
  static const JsonPath<TimeUnit> durationUnit = JsonPath.internal(["durationUnit"], "/durationUnit");
  static const JsonPath<int> durationAmount = JsonPath.internal(["durationAmount"], "/durationAmount");
  static const JsonPath<TimeUnit> delayUnit = JsonPath.internal(["delayUnit"], "/delayUnit");
  static const JsonPath<int> delayAmount = JsonPath.internal(["delayAmount"], "/delayAmount");
  static const JsonPath<String> giphyUrl = JsonPath.internal(["giphyUrl"], "/giphyUrl");
  static const JsonPath<String> caption = JsonPath.internal(["caption"], "/caption");
  static const JsonPath<String> text = JsonPath.internal(["text"], "/text");
  static final Set<JsonPath> values = {
    dismissible, repeatsFor, showEvery, delivery, durationUnit, durationAmount, delayUnit, delayAmount, giphyUrl, caption, text
  };
}


const GiphyContentRef = MSchemaRef("sunny", "content", "giphyContent", "0.0.1", "ephemeral");

typedef _GiphyContentConstructor = IGiphyContent Function({   required bool? dismissible, 
  int? repeatsFor, 
  int? showEvery, 
  required IContentDelivery? delivery, 
  TimeUnit? durationUnit, 
  int? durationAmount, 
  TimeUnit? delayUnit, 
  int? delayAmount, 
  required String? giphyUrl, 
  String? caption, 
  String? text
 });
typedef _GiphyContentFromJson = IGiphyContent Function(dynamic any);