// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';

import '../model/flow_query.dart';


abstract class IGroupFlowQuery implements IFlowQuery {
  /// Property getter and setter for groupIdentifier: 
  String? get groupIdentifier;
  set groupIdentifier(String? groupIdentifier);

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IGroupFlowQuery clone();

  @override
  Set<String> get mfields => GroupFlowQueryFields.values;

}

class GroupFlowQueryFields {
  
  static const groupIdentifier = "groupIdentifier";
  static const Set<String> values = {
    groupIdentifier
  };
}

class GroupFlowQueryPaths {
  
  static const JsonPath<String> groupIdentifier = JsonPath.internal(["groupIdentifier"], "/groupIdentifier");
  static final Set<JsonPath> values = {
    groupIdentifier
  };
}


const GroupFlowQueryRef = MSchemaRef("sunny", "groupFlow", "groupFlowQuery", "0.0.1", "ephemeral");