// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../waypoints_ext.dart';

import '../model/expression.dart';


abstract class ILiteralExpression
  implements IExpression {

  static late _LiteralExpressionConstructor of;
  static late _LiteralExpressionFromJson fromJson;

  /// Property getter and setter for literalValue: 
  dynamic? get literalValue;
  set literalValue(dynamic? literalValue);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  ILiteralExpression clone();

  @override
  Set<String> get mfields => LiteralExpressionFields.values;

}

class LiteralExpressionFields {
  static const literalValue = "literalValue";
  static const Set<String> values = {
    literalValue
  };
}

class LiteralExpressionPaths {
  static const JsonPath<dynamic> literalValue = JsonPath.internal(["literalValue"], "/literalValue");
  static final Set<JsonPath> values = {
    literalValue
  };
}


const LiteralExpressionRef = MSchemaRef("sunny", "waypointsBuilder", "literalExpression", "0.0.1", "ephemeral");

typedef _LiteralExpressionConstructor = ILiteralExpression Function({   required dynamic? literalValue
 });
typedef _LiteralExpressionFromJson = ILiteralExpression Function(dynamic any);