// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../waypoints_ext.dart';



class ILocale extends MLiteral<String> {
  static late ILocale? Function(dynamic any) fromJson;
  static late ILocaleValues values;
  static ILocale get enUs_ => values.enUs_;
  static ILocale get enCa_ => values.enCa_;
  static ILocale get enGb_ => values.enGb_;
  static ILocale get enAu_ => values.enAu_;
  static ILocale get enNz_ => values.enNz_;
  static ILocale get frCa_ => values.frCa_;
  static ILocale get frFr_ => values.frFr_;

  final bool isKnown;
  @protected
  const ILocale.internal(String value): isKnown = true, super(value);
  const ILocale.unknown(String value): isKnown = false, super(value);
}

class ILocaleValues extends ListDelegateMixin<ILocale> {
    final ILocale enUs_;
    final ILocale enCa_;
    final ILocale enGb_;
    final ILocale enAu_;
    final ILocale enNz_;
    final ILocale frCa_;
    final ILocale frFr_;

  @override
  final List<ILocale> delegate;

  ILocaleValues(this.enUs_,
      this.enCa_,
      this.enGb_,
      this.enAu_,
      this.enNz_,
      this.frCa_,
      this.frFr_) : delegate = List.unmodifiable([enUs_,enCa_,enGb_,enAu_,enNz_,frCa_,frFr_]);
}
