// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../waypoints_ext.dart';



abstract class IPrioritizedMember
  implements MModel {

  static late _PrioritizedMemberConstructor of;
  static late _PrioritizedMemberFromJson fromJson;

  /// Property getter and setter for contactId: 
  String? get contactId;
  set contactId(String? contactId);


  /// Property getter and setter for priority: 
  int? get priority;
  set priority(int? priority);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IPrioritizedMember clone();

  @override
  Set<String> get mfields => PrioritizedMemberFields.values;

}

class PrioritizedMemberFields {
  static const contactId = "contactId";
  static const priority = "priority";
  static const Set<String> values = {
    contactId, priority
  };
}

class PrioritizedMemberPaths {
  static const JsonPath<String> contactId = JsonPath.internal(["contactId"], "/contactId");
  static const JsonPath<int> priority = JsonPath.internal(["priority"], "/priority");
  static final Set<JsonPath> values = {
    contactId, priority
  };
}


const PrioritizedMemberRef = MSchemaRef("sunny", "groupFlow", "prioritizedMember", "0.0.1", "ephemeral");

typedef _PrioritizedMemberConstructor = IPrioritizedMember Function({   required String? contactId, 
  required int? priority
 });
typedef _PrioritizedMemberFromJson = IPrioritizedMember Function(dynamic any);