// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../waypoints_ext.dart';



abstract class IRange
  implements MModel {

  static late _RangeConstructor of;
  static late _RangeFromJson fromJson;

  /// Property getter and setter for start: 
  num? get start;
  set start(num? start);


  /// Property getter and setter for end: 
  num? get end;
  set end(num? end);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IRange clone();

  @override
  Set<String> get mfields => RangeFields.values;

}

class RangeFields {
  static const start = "start";
  static const end = "end";
  static const Set<String> values = {
    start, end
  };
}

class RangePaths {
  static const JsonPath<num> start = JsonPath.internal(["start"], "/start");
  static const JsonPath<num> end = JsonPath.internal(["end"], "/end");
  static final Set<JsonPath> values = {
    start, end
  };
}


const RangeRef = MSchemaRef("mverse", "waypoints", "range", "0.0.1", "ephemeral");

typedef _RangeConstructor = IRange Function({   num? start, 
  num? end
 });
typedef _RangeFromJson = IRange Function(dynamic any);