// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../waypoints_ext.dart';

import '../model/template_set.dart';


abstract class IReachOutContent
  implements MModel {

  static late _ReachOutContentConstructor of;
  static late _ReachOutContentFromJson fromJson;

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IReachOutContent clone();

}


const ReachOutContentRef = MSchemaRef("slick", "sunny", "reachOutContent", "0.0.1", "ephemeral");

typedef _ReachOutContentConstructor = IReachOutContent Function();
typedef _ReachOutContentFromJson = IReachOutContent Function(dynamic any);