// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../waypoints_ext.dart';

import 'package:sunny_service_stubs/models/m_entity/model/m_schema_definition.dart';


abstract class IRenderContext
  implements MModel {

  static late _RenderContextConstructor of;
  static late _RenderContextFromJson fromJson;

  /// Property getter and setter for properties: 
  Map<String, IMSchemaDefinition>? get properties;
  set properties(Map<String, IMSchemaDefinition>? properties);


  /// Property getter and setter for adhocProperties: 
  Map<String, String>? get adhocProperties;
  set adhocProperties(Map<String, String>? adhocProperties);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IRenderContext clone();

  @override
  Set<String> get mfields => RenderContextFields.values;

}

class RenderContextFields {
  static const properties = "properties";
  static const adhocProperties = "adhocProperties";
  static const Set<String> values = {
    properties, adhocProperties
  };
}

class RenderContextPaths {
  static const JsonPath<Map<String, IMSchemaDefinition>> properties = JsonPath.internal(["properties"], "/properties");
  static const JsonPath<Map<String, String>> adhocProperties = JsonPath.internal(["adhocProperties"], "/adhocProperties");
  static final Set<JsonPath> values = {
    properties, adhocProperties
  };
}


const RenderContextRef = MSchemaRef("sunny", "content", "renderContext", "0.0.1", "ephemeral");

typedef _RenderContextConstructor = IRenderContext Function({   required Map<String, IMSchemaDefinition>? properties, 
  required Map<String, String>? adhocProperties
 });
typedef _RenderContextFromJson = IRenderContext Function(dynamic any);