// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';

import '../../m_entity/model/m_schema_definition.dart';


abstract class IRenderContext implements MModel {
  /// Property getter and setter for properties: 
  Map<String, IMSchemaDefinition>? get properties;
  

  /// Property getter and setter for adhocProperties: 
  Map<String, String>? get adhocProperties;
  

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IRenderContext clone();

  @override
  Set<String> get mfields => RenderContextFields.values;

}

class RenderContextFields {
  
  static const properties = "properties";
  static const adhocProperties = "adhocProperties";
  static const Set<String> values = {
    properties, adhocProperties
  };
}

class RenderContextPaths {
  
  static const JsonPath<Map<String, IMSchemaDefinition>> properties = JsonPath.internal(["properties"], "/properties");
  static const JsonPath<Map<String, String>> adhocProperties = JsonPath.internal(["adhocProperties"], "/adhocProperties");
  static final Set<JsonPath> values = {
    properties, adhocProperties
  };
}


const RenderContextRef = MSchemaRef("sunny", "content", "renderContext", "0.0.1", "ephemeral");