// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';



abstract class IResourceFlowInfo implements MModel {
  /// Property getter and setter for resourceName: 
  String? get resourceName;
  set resourceName(String? resourceName);

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IResourceFlowInfo clone();

  @override
  Set<String> get mfields => ResourceFlowInfoFields.values;

}

class ResourceFlowInfoFields {
  
  static const resourceName = "resourceName";
  static const Set<String> values = {
    resourceName
  };
}

class ResourceFlowInfoPaths {
  
  static const JsonPath<String> resourceName = JsonPath.internal(["resourceName"], "/resourceName");
  static final Set<JsonPath> values = {
    resourceName
  };
}


const ResourceFlowInfoRef = MSchemaRef("sunny", "waypointsBuilder", "resourceFlowInfo", "0.0.1", "ephemeral");