// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../waypoints_ext.dart';



abstract class IRoutingTaskInfo
  implements MModel {

  static late _RoutingTaskInfoConstructor of;
  static late _RoutingTaskInfoFromJson fromJson;

  /// Property getter and setter for possibleOutcomes: 
  List<String>? get possibleOutcomes;
  set possibleOutcomes(List<String>? possibleOutcomes);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IRoutingTaskInfo clone();

  @override
  Set<String> get mfields => RoutingTaskInfoFields.values;

}

class RoutingTaskInfoFields {
  static const possibleOutcomes = "possibleOutcomes";
  static const Set<String> values = {
    possibleOutcomes
  };
}

class RoutingTaskInfoPaths {
  static const JsonPath<List<String>> possibleOutcomes = JsonPath.internal(["possibleOutcomes"], "/possibleOutcomes");
  static final Set<JsonPath> values = {
    possibleOutcomes
  };
}


const RoutingTaskInfoRef = MSchemaRef("sunny", "waypointsBuilder", "routingTaskInfo", "0.0.1", "ephemeral");

typedef _RoutingTaskInfoConstructor = IRoutingTaskInfo Function({   required List<String>? possibleOutcomes
 });
typedef _RoutingTaskInfoFromJson = IRoutingTaskInfo Function(dynamic any);