// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';

import '../model/smart_group_filter.dart';
import 'package:sunny_sdk_core/sunny_sdk_core.dart';


abstract class ISmartGroupFlowInfo implements MModel {
  /// Property getter and setter for name: 
  String? get name;
  

  /// Property getter and setter for memberLabel: 
  String? get memberLabel;
  

  /// Property getter and setter for description: 
  String? get description;
  

  /// Property getter and setter for groupFact: 
  MSchemaRef? get groupFact;
  

  /// Property getter and setter for filters: 
  List<ISmartGroupFilter>? get filters;
  

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  ISmartGroupFlowInfo clone();

  @override
  Set<String> get mfields => SmartGroupFlowInfoFields.values;

}

class SmartGroupFlowInfoFields {
  
  static const name = "name";
  static const memberLabel = "memberLabel";
  static const description = "description";
  static const groupFact = "groupFact";
  static const filters = "filters";
  static const Set<String> values = {
    name, memberLabel, description, groupFact, filters
  };
}

class SmartGroupFlowInfoPaths {
  
  static const JsonPath<String> name = JsonPath.internal(["name"], "/name");
  static const JsonPath<String> memberLabel = JsonPath.internal(["memberLabel"], "/memberLabel");
  static const JsonPath<String> description = JsonPath.internal(["description"], "/description");
  static const JsonPath<MSchemaRef> groupFact = JsonPath.internal(["groupFact"], "/groupFact");
  static const JsonPath<List<ISmartGroupFilter>> filters = JsonPath.internal(["filters"], "/filters");
  static final Set<JsonPath> values = {
    name, memberLabel, description, groupFact, filters
  };
}


const SmartGroupFlowInfoRef = MSchemaRef("sunny", "groupFlow", "smartGroupFlowInfo", "0.0.1", "ephemeral");