// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../waypoints_ext.dart';

import 'package:sunny_sdk_core/sunny_sdk_core.dart';


abstract class IStartThreadRequest
  implements MModel {

  static late _StartThreadRequestConstructor of;
  static late _StartThreadRequestFromJson fromJson;

  /// Property getter and setter for flowGraphId: 
  String? get flowGraphId;
  set flowGraphId(String? flowGraphId);


  /// Property getter and setter for subjects: 
  Map<String, MEntity>? get subjects;
  set subjects(Map<String, MEntity>? subjects);


  /// Property getter and setter for state: 
  MModel? get state;
  set state(MModel? state);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IStartThreadRequest clone();

  @override
  Set<String> get mfields => StartThreadRequestFields.values;

}

class StartThreadRequestFields {
  static const flowGraphId = "flowGraphId";
  static const subjects = "subjects";
  static const state = "state";
  static const Set<String> values = {
    flowGraphId, subjects, state
  };
}

class StartThreadRequestPaths {
  static const JsonPath<String> flowGraphId = JsonPath.internal(["flowGraphId"], "/flowGraphId");
  static const JsonPath<Map<String, MEntity>> subjects = JsonPath.internal(["subjects"], "/subjects");
  static const JsonPath<MModel> state = JsonPath.internal(["state"], "/state");
  static final Set<JsonPath> values = {
    flowGraphId, subjects, state
  };
}


const StartThreadRequestRef = MSchemaRef("sunny", "waypoints", "startThreadRequest", "0.0.1", "ephemeral");

typedef _StartThreadRequestConstructor = IStartThreadRequest Function({   required String? flowGraphId, 
  required Map<String, MEntity>? subjects, 
  MModel? state
 });
typedef _StartThreadRequestFromJson = IStartThreadRequest Function(dynamic any);