// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../waypoints_ext.dart';

import '../model/sunny_bundle.dart';


abstract class ISunnyBundles
  implements MModel {

  static late _SunnyBundlesConstructor of;
  static late _SunnyBundlesFromJson fromJson;

  /// Property getter and setter for count: 
  int? get count;
  set count(int? count);


  /// Property getter and setter for data: 
  List<ISunnyBundle>? get data;
  set data(List<ISunnyBundle>? data);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  ISunnyBundles clone();

  @override
  Set<String> get mfields => SunnyBundlesFields.values;

}

class SunnyBundlesFields {
  static const count = "count";
  static const data = "data";
  static const Set<String> values = {
    count, data
  };
}

class SunnyBundlesPaths {
  static const JsonPath<int> count = JsonPath.internal(["count"], "/count");
  static const JsonPath<List<ISunnyBundle>> data = JsonPath.internal(["data"], "/data");
  static final Set<JsonPath> values = {
    count, data
  };
}


const SunnyBundlesRef = MSchemaRef("sunny", "waypointsBuilder", "sunnyBundles", "0.0.1", "ephemeral");

typedef _SunnyBundlesConstructor = ISunnyBundles Function({   required int? count, 
  required List<ISunnyBundle>? data
 });
typedef _SunnyBundlesFromJson = ISunnyBundles Function(dynamic any);