// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../waypoints_ext.dart';

import '../model/sunny_publisher.dart';


abstract class ISunnyPublishers
  implements MModel {

  static late _SunnyPublishersConstructor of;
  static late _SunnyPublishersFromJson fromJson;

  /// Property getter and setter for count: 
  int? get count;
  set count(int? count);


  /// Property getter and setter for data: 
  List<ISunnyPublisher>? get data;
  set data(List<ISunnyPublisher>? data);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  ISunnyPublishers clone();

  @override
  Set<String> get mfields => SunnyPublishersFields.values;

}

class SunnyPublishersFields {
  static const count = "count";
  static const data = "data";
  static const Set<String> values = {
    count, data
  };
}

class SunnyPublishersPaths {
  static const JsonPath<int> count = JsonPath.internal(["count"], "/count");
  static const JsonPath<List<ISunnyPublisher>> data = JsonPath.internal(["data"], "/data");
  static final Set<JsonPath> values = {
    count, data
  };
}


const SunnyPublishersRef = MSchemaRef("sunny", "waypointsBuilder", "sunnyPublishers", "0.0.1", "ephemeral");

typedef _SunnyPublishersConstructor = ISunnyPublishers Function({   required int? count, 
  required List<ISunnyPublisher>? data
 });
typedef _SunnyPublishersFromJson = ISunnyPublishers Function(dynamic any);