// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../truman_ext.dart';



class IMemberLevel extends MLiteral<String> {
  static late IMemberLevel? Function(dynamic any) fromJson;
  static late IMemberLevelValues values;
  static IMemberLevel get newEnrollee_ => values.newEnrollee_;
  static IMemberLevel get wellnessAdvocate_ => values.wellnessAdvocate_;
  static IMemberLevel get manager_ => values.manager_;
  static IMemberLevel get director_ => values.director_;
  static IMemberLevel get executive_ => values.executive_;
  static IMemberLevel get elite_ => values.elite_;
  static IMemberLevel get premier_ => values.premier_;
  static IMemberLevel get silver_ => values.silver_;
  static IMemberLevel get gold_ => values.gold_;
  static IMemberLevel get platinum_ => values.platinum_;
  static IMemberLevel get diamond_ => values.diamond_;
  static IMemberLevel get blueDiamond_ => values.blueDiamond_;
  static IMemberLevel get presidentialDiamond_ => values.presidentialDiamond_;
  static IMemberLevel get doubleDiamond_ => values.doubleDiamond_;
  static IMemberLevel get doubleBlueDiamond_ => values.doubleBlueDiamond_;
  static IMemberLevel get doublePresidentialDiamond_ => values.doublePresidentialDiamond_;

  final bool isKnown;
  @protected
  const IMemberLevel.internal(String value): isKnown = true, super(value);
  const IMemberLevel.unknown(String value): isKnown = false, super(value);
}

class IMemberLevelValues extends ListDelegateMixin<IMemberLevel> {
    final IMemberLevel newEnrollee_;
    final IMemberLevel wellnessAdvocate_;
    final IMemberLevel manager_;
    final IMemberLevel director_;
    final IMemberLevel executive_;
    final IMemberLevel elite_;
    final IMemberLevel premier_;
    final IMemberLevel silver_;
    final IMemberLevel gold_;
    final IMemberLevel platinum_;
    final IMemberLevel diamond_;
    final IMemberLevel blueDiamond_;
    final IMemberLevel presidentialDiamond_;
    final IMemberLevel doubleDiamond_;
    final IMemberLevel doubleBlueDiamond_;
    final IMemberLevel doublePresidentialDiamond_;

  @override
  final List<IMemberLevel> delegate;

  IMemberLevelValues(this.newEnrollee_,
      this.wellnessAdvocate_,
      this.manager_,
      this.director_,
      this.executive_,
      this.elite_,
      this.premier_,
      this.silver_,
      this.gold_,
      this.platinum_,
      this.diamond_,
      this.blueDiamond_,
      this.presidentialDiamond_,
      this.doubleDiamond_,
      this.doubleBlueDiamond_,
      this.doublePresidentialDiamond_) : delegate = List.unmodifiable([newEnrollee_,wellnessAdvocate_,manager_,director_,executive_,elite_,premier_,silver_,gold_,platinum_,diamond_,blueDiamond_,presidentialDiamond_,doubleDiamond_,doubleBlueDiamond_,doublePresidentialDiamond_]);
}
