// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../truman_ext.dart';

import '../model/the_why.dart';


abstract class ITheWhyList
  implements MModel, MModelList<ITheWhy> {

  static late _TheWhyListConstructor of;
  static late _TheWhyListFromJson fromJson;

  /// Property getter and setter for count: 
  int? get count;
  set count(int? count);


  /// Property getter and setter for data: 
  List<ITheWhy>? get data;
  set data(List<ITheWhy>? data);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  ITheWhyList clone();

  @override
  Set<String> get mfields => TheWhyListFields.values;

}

class TheWhyListFields {
  static const count = "count";
  static const data = "data";
  static const Set<String> values = {
    count, data
  };
}

class TheWhyListPaths {
  static const JsonPath<int> count = JsonPath.internal(["count"], "/count");
  static const JsonPath<List<ITheWhy>> data = JsonPath.internal(["data"], "/data");
  static final Set<JsonPath> values = {
    count, data
  };
}


const TheWhyListRef = MSchemaRef("truman", "sunny", "theWhyList", "0.0.1", "ephemeral");

typedef _TheWhyListConstructor = ITheWhyList Function({   int? count, 
  List<ITheWhy>? data
 });
typedef _TheWhyListFromJson = ITheWhyList Function(dynamic any);