// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../truman_ext.dart';

import '../model/truman_health_info.dart';


abstract class ITrumanHealthInfoList
  implements MModel, MModelList<ITrumanHealthInfo> {

  static late _TrumanHealthInfoListConstructor of;
  static late _TrumanHealthInfoListFromJson fromJson;

  /// Property getter and setter for count: 
  int? get count;
  set count(int? count);


  /// Property getter and setter for data: 
  List<ITrumanHealthInfo>? get data;
  set data(List<ITrumanHealthInfo>? data);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  ITrumanHealthInfoList clone();

  @override
  Set<String> get mfields => TrumanHealthInfoListFields.values;

}

class TrumanHealthInfoListFields {
  static const count = "count";
  static const data = "data";
  static const Set<String> values = {
    count, data
  };
}

class TrumanHealthInfoListPaths {
  static const JsonPath<int> count = JsonPath.internal(["count"], "/count");
  static const JsonPath<List<ITrumanHealthInfo>> data = JsonPath.internal(["data"], "/data");
  static final Set<JsonPath> values = {
    count, data
  };
}


const TrumanHealthInfoListRef = MSchemaRef("truman", "sunny", "trumanHealthInfoList", "0.0.1", "ephemeral");

typedef _TrumanHealthInfoListConstructor = ITrumanHealthInfoList Function({   int? count, 
  List<ITrumanHealthInfo>? data
 });
typedef _TrumanHealthInfoListFromJson = ITrumanHealthInfoList Function(dynamic any);