// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../smart_dates_ext.dart';



class ISeekDirection extends MLiteral<String> {
  static late ISeekDirection? Function(dynamic any) fromJson;
  static late ISeekDirectionValues values;
  static ISeekDirection get next_ => values.next_;
  static ISeekDirection get last_ => values.last_;

  final bool isKnown;
  @protected
  const ISeekDirection.internal(String value): isKnown = true, super(value);
  const ISeekDirection.unknown(String value): isKnown = false, super(value);
}

class ISeekDirectionValues extends ListDelegateMixin<ISeekDirection> {
    final ISeekDirection next_;
    final ISeekDirection last_;

  @override
  final List<ISeekDirection> delegate;

  ISeekDirectionValues(this.next_,
      this.last_) : delegate = List.unmodifiable([next_,last_]);
}
