// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';

import '../model/m_operation_definition.dart';


abstract class IMOperationDefinitionList implements MModel {
  /// Property getter and setter for data: 
  List<IMOperationDefinition>? get data;
  

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IMOperationDefinitionList clone();

  @override
  Set<String> get mfields => MOperationDefinitionListFields.values;

}

class MOperationDefinitionListFields {
  
  static const data = "data";
  static const Set<String> values = {
    data
  };
}

class MOperationDefinitionListPaths {
  
  static const JsonPath<List<IMOperationDefinition>> data = JsonPath.internal(["data"], "/data");
  static final Set<JsonPath> values = {
    data
  };
}


const MOperationDefinitionListRef = MSchemaRef("mverse", "mthing", "mOperationDefinitionList", "0.0.1", "ephemeral");