// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../m_entity_ext.dart';

import '../model/m_schema_property.dart';


abstract class IMSchemaDefinition
  implements MModel, MSchemaDefinitionExt {

  static late _MSchemaDefinitionConstructor of;
  static late _MSchemaDefinitionFromJson fromJson;

  /// Property getter and setter for schemaURI: 
  Uri? get schemaURI;
  set schemaURI(Uri? schemaURI);


  /// Property getter and setter for properties: 
  List<IMSchemaProperty>? get properties;
  set properties(List<IMSchemaProperty>? properties);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IMSchemaDefinition clone();

  @override
  Set<String> get mfields => MSchemaDefinitionFields.values;

}

class MSchemaDefinitionFields {
  static const schemaURI = "schemaURI";
  static const properties = "properties";
  static const Set<String> values = {
    schemaURI, properties
  };
}

class MSchemaDefinitionPaths {
  static const JsonPath<Uri> schemaURI = JsonPath.internal(["schemaURI"], "/schemaURI");
  static const JsonPath<List<IMSchemaProperty>> properties = JsonPath.internal(["properties"], "/properties");
  static final Set<JsonPath> values = {
    schemaURI, properties
  };
}


const MSchemaDefinitionRef = MSchemaRef("mverse", "mthing", "mSchemaDefinition", "0.0.1", "ephemeral");

typedef _MSchemaDefinitionConstructor = IMSchemaDefinition Function({   required Uri? schemaURI, 
  required List<IMSchemaProperty>? properties
 });
typedef _MSchemaDefinitionFromJson = IMSchemaDefinition Function(dynamic any);