// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';

import '../model/m_schema_property.dart';


abstract class IStringSelectProperty implements IMSchemaProperty {
  /// Property getter and setter for options: 
  List<String>? get options;
  set options(List<String>? options);

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IStringSelectProperty clone();

  @override
  Set<String> get mfields => StringSelectPropertyFields.values;

}

class StringSelectPropertyFields {
  
  static const type = "type";
  static const path = "path";
  static const label = "label";
  static const description = "description";
  static const uri = "uri";
  static const baseCode = "baseCode";
  static const isRequired = "isRequired";
  static const options = "options";
  static const Set<String> values = {
    type, path, label, description, uri, baseCode, isRequired, options
  };
}

class StringSelectPropertyPaths {
  
  static const JsonPath<String> type = JsonPath.internal(["type"], "/type");
  static const JsonPath<String> path = JsonPath.internal(["path"], "/path");
  static const JsonPath<String> label = JsonPath.internal(["label"], "/label");
  static const JsonPath<String> description = JsonPath.internal(["description"], "/description");
  static const JsonPath<Uri> uri = JsonPath.internal(["uri"], "/uri");
  static const JsonPath<String> baseCode = JsonPath.internal(["baseCode"], "/baseCode");
  static const JsonPath<bool> isRequired = JsonPath.internal(["isRequired"], "/isRequired");
  static const JsonPath<List<String>> options = JsonPath.internal(["options"], "/options");
  static final Set<JsonPath> values = {
    type, path, label, description, uri, baseCode, isRequired, options
  };
}


const StringSelectPropertyRef = MSchemaRef("mverse", "mthing", "stringSelectProperty", "0.0.1", "ephemeral");