// ignore_for_file: avoid_renaming_method_parameters,duplicate_import, unused_import, unnecessary_null_comparison, unnecessary_non_null_assertion

/// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'dart:convert';
import 'package:sunny_sdk_core/api_exports.dart';

import 'package:sunny_sdk_core/sunny_sdk_core.dart';
import '../model/gift.dart';
import '../model/gift_list.dart';

import '../facts.dart';


///
/// DO NOT MODIFY
///
/// GENERATED API OPERATIONS
///
abstract class IGiftApi extends Repository<IGift> /* sunny:fact:schema:gift:0.0.1@mverse*/{

  @override
  MSchemaRef get mtype => GiftRef;

  Future<IGift> create(IGift gift,);
    
  Future<DeleteResponse> delete(String id,);
    
  Future<IGiftList> list({ double? limit,  double? offset });
    
  Future<IGift> load(String id,);
    
  Future<ChangeResult> update(String id, IGift gift,);
    
}