// ignore_for_file: avoid_renaming_method_parameters,duplicate_import, unused_import, unnecessary_null_comparison, unnecessary_non_null_assertion

/// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'dart:convert';
import 'package:meta/meta.dart';
import 'package:sunny_sdk_core/api_exports.dart';

import 'package:sunny_sdk_core/sunny_sdk_core.dart';
import '../model/organization.dart';
import '../model/organization_list.dart';

import '../facts.dart';


///
/// DO NOT MODIFY
///
/// GENERATED API OPERATIONS
///
abstract class IOrganizationApi extends Repository<IOrganization> /* sunny:fact:schema:organization:0.0.1@abstract*/{

  @override
  MSchemaRef get mtype => OrganizationRef;

  Future<IOrganization> create(IOrganization organization,);
    
  Future<DeleteResponse> delete(String id,);
    
  Future<IOrganizationList> list({ double? limit,  double? offset });
    
  Future<IOrganization> load(String id,);
    
  Future<ChangeResult> update(String id, IOrganization organization,);
    
}