// ignore_for_file: avoid_renaming_method_parameters,duplicate_import, unused_import, unnecessary_null_comparison, unnecessary_non_null_assertion

/// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'dart:convert';
import 'package:meta/meta.dart';
import 'package:sunny_sdk_core/api_exports.dart';

import 'package:sunny_sdk_core/sunny_sdk_core.dart';
import '../model/tradition.dart';
import '../model/tradition_list.dart';

import '../facts.dart';


///
/// DO NOT MODIFY
///
/// GENERATED API OPERATIONS
///
abstract class ITraditionApi extends Repository<ITradition> /* sunny:fact:schema:tradition:0.0.1@mverse*/{

  @override
  MSchemaRef get mtype => TraditionRef;

  Future<ITradition> create(ITradition tradition,);
    
  Future<DeleteResponse> delete(String id,);
    
  Future<ITraditionList> list({ double? limit,  double? offset });
    
  Future<ITradition> load(String id,);
    
  Future<ChangeResult> update(String id, ITradition tradition,);
    
}