// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../facts_ext.dart';

import '../model/fact.dart';
import '../model/task_fact_for_m_model.dart';
import 'package:sunny_service_stubs/models/reliveit/model/relive_it_contact.dart';


abstract class IBirthday
  implements IFact {

  static late _BirthdayConstructor of;
  static late _BirthdayFromJson fromJson;

  /// Property getter and setter for contactKey: 
  MKey? get contactKey;
  set contactKey(MKey? contactKey);


  /// Property getter and setter for birthday: 
  FlexiDate? get birthday;
  set birthday(FlexiDate? birthday);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IBirthday clone();

  @override
  Set<String> get mfields => BirthdayFields.values;

}

class BirthdayFields {
  static const creator = "creator";
  static const dateCreated = "dateCreated";
  static const assistedTask = "assistedTask";
  static const contactKey = "contactKey";
  static const birthday = "birthday";
  static const Set<String> values = {
    creator, dateCreated, assistedTask, contactKey, birthday
  };
}

class BirthdayPaths {
  static const JsonPath<IReliveItContact> creator = JsonPath.internal(["creator"], "/creator");
  static const JsonPath<DateTime> dateCreated = JsonPath.internal(["dateCreated"], "/dateCreated");
  static const JsonPath<ITaskFactForMModel> assistedTask = JsonPath.internal(["assistedTask"], "/assistedTask");
  static const JsonPath<MKey> contactKey = JsonPath.internal(["contactKey"], "/contactKey");
  static const JsonPath<FlexiDate> birthday = JsonPath.internal(["birthday"], "/birthday");
  static final Set<JsonPath> values = {
    creator, dateCreated, assistedTask, contactKey, birthday
  };
}


const BirthdayRef = MSchemaRef("sunny", "fact", "birthday", "0.0.1", "mverse");

typedef _BirthdayConstructor = IBirthday Function({   IReliveItContact? creator, 
  required DateTime? dateCreated, 
  ITaskFactForMModel? assistedTask, 
  required MKey? contactKey, 
  required FlexiDate? birthday
 });
typedef _BirthdayFromJson = IBirthday Function(dynamic any);