// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../facts_ext.dart';

import '../model/contact_extended_props.dart';


abstract class IContactExtendedPropsList
  implements MModel, MModelList<IContactExtendedProps> {

  static late _ContactExtendedPropsListConstructor of;
  static late _ContactExtendedPropsListFromJson fromJson;

  /// Property getter and setter for count: 
  int? get count;
  set count(int? count);


  /// Property getter and setter for data: 
  List<IContactExtendedProps>? get data;
  set data(List<IContactExtendedProps>? data);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IContactExtendedPropsList clone();

  @override
  Set<String> get mfields => ContactExtendedPropsListFields.values;

}

class ContactExtendedPropsListFields {
  static const count = "count";
  static const data = "data";
  static const Set<String> values = {
    count, data
  };
}

class ContactExtendedPropsListPaths {
  static const JsonPath<int> count = JsonPath.internal(["count"], "/count");
  static const JsonPath<List<IContactExtendedProps>> data = JsonPath.internal(["data"], "/data");
  static final Set<JsonPath> values = {
    count, data
  };
}


const ContactExtendedPropsListRef = MSchemaRef("sunny", "fact", "contactExtendedPropsList", "0.0.1", "ephemeral");

typedef _ContactExtendedPropsListConstructor = IContactExtendedPropsList Function({   int? count, 
  List<IContactExtendedProps>? data
 });
typedef _ContactExtendedPropsListFromJson = IContactExtendedPropsList Function(dynamic any);