// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';

import '../../reliveit/model/relive_it_contact.dart';
import '../model/fact.dart';
import '../model/gender.dart';
import '../model/task_fact_for_m_model.dart';
import 'package:sunny_sdk_core/sunny_sdk_core.dart';


abstract class IContactExtendedProps implements IFact {
  /// Property getter and setter for contactKey: 
  MKey? get contactKey;
  

  /// Property getter and setter for gender: 
  IGender? get gender;
  

  /// Property getter and setter for nickName: 
  String? get nickName;
  

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IContactExtendedProps clone();

  @override
  Set<String> get mfields => ContactExtendedPropsFields.values;

}

class ContactExtendedPropsFields {
  
  static const creator = "creator";
  static const dateCreated = "dateCreated";
  static const assistedTask = "assistedTask";
  static const contactKey = "contactKey";
  static const gender = "gender";
  static const nickName = "nickName";
  static const Set<String> values = {
    creator, dateCreated, assistedTask, contactKey, gender, nickName
  };
}

class ContactExtendedPropsPaths {
  
  static const JsonPath<IReliveItContact> creator = JsonPath.internal(["creator"], "/creator");
  static const JsonPath<DateTime> dateCreated = JsonPath.internal(["dateCreated"], "/dateCreated");
  static const JsonPath<ITaskFactForMModel> assistedTask = JsonPath.internal(["assistedTask"], "/assistedTask");
  static const JsonPath<MKey> contactKey = JsonPath.internal(["contactKey"], "/contactKey");
  static const JsonPath<IGender> gender = JsonPath.internal(["gender"], "/gender");
  static const JsonPath<String> nickName = JsonPath.internal(["nickName"], "/nickName");
  static final Set<JsonPath> values = {
    creator, dateCreated, assistedTask, contactKey, gender, nickName
  };
}


const ContactExtendedPropsRef = MSchemaRef("sunny", "fact", "contactExtendedProps", "0.0.1", "mverse");