// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';

import '../../contact_v2/model/physical_location.dart';
import '../../waypoints/model/image_content.dart';
import '../model/organization.dart';
import '../model/phase.dart';
import 'package:sunny_sdk_core/sunny_sdk_core.dart';


abstract class IEmployer implements IOrganization {
  /// Property getter and setter for address: 
  IPhysicalLocation? get address;
  set address(IPhysicalLocation? address);

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IEmployer clone();

  @override
  Set<String> get mfields => EmployerFields.values;

}

class EmployerFields {
  
  static const name = "name";
  static const logo = "logo";
  static const phases = "phases";
  static const parent = "parent";
  static const address = "address";
  static const Set<String> values = {
    name, logo, phases, parent, address
  };
}

class EmployerPaths {
  
  static const JsonPath<String> name = JsonPath.internal(["name"], "/name");
  static const JsonPath<IImageContent> logo = JsonPath.internal(["logo"], "/logo");
  static const JsonPath<List<IPhase>> phases = JsonPath.internal(["phases"], "/phases");
  static const JsonPath<List<MKey>> parent = JsonPath.internal(["parent"], "/parent");
  static const JsonPath<IPhysicalLocation> address = JsonPath.internal(["address"], "/address");
  static final Set<JsonPath> values = {
    name, logo, phases, parent, address
  };
}


const EmployerRef = MSchemaRef("sunny", "fact", "employer", "0.0.1", "mverse");