// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../facts_ext.dart';

import '../model/hometown.dart';


abstract class IHometownList
  implements MModel, MModelList<IHometown> {

  static late _HometownListConstructor of;
  static late _HometownListFromJson fromJson;

  /// Property getter and setter for count: 
  int? get count;
  set count(int? count);


  /// Property getter and setter for data: 
  List<IHometown>? get data;
  set data(List<IHometown>? data);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IHometownList clone();

  @override
  Set<String> get mfields => HometownListFields.values;

}

class HometownListFields {
  static const count = "count";
  static const data = "data";
  static const Set<String> values = {
    count, data
  };
}

class HometownListPaths {
  static const JsonPath<int> count = JsonPath.internal(["count"], "/count");
  static const JsonPath<List<IHometown>> data = JsonPath.internal(["data"], "/data");
  static final Set<JsonPath> values = {
    count, data
  };
}


const HometownListRef = MSchemaRef("sunny", "fact", "hometownList", "0.0.1", "ephemeral");

typedef _HometownListConstructor = IHometownList Function({   int? count, 
  List<IHometown>? data
 });
typedef _HometownListFromJson = IHometownList Function(dynamic any);