// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../facts_ext.dart';

import '../model/membership.dart';


abstract class IMembershipList
  implements MModel, MModelList<IMembership> {

  static late _MembershipListConstructor of;
  static late _MembershipListFromJson fromJson;

  /// Property getter and setter for count: 
  int? get count;
  set count(int? count);


  /// Property getter and setter for data: 
  List<IMembership>? get data;
  set data(List<IMembership>? data);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IMembershipList clone();

  @override
  Set<String> get mfields => MembershipListFields.values;

}

class MembershipListFields {
  static const count = "count";
  static const data = "data";
  static const Set<String> values = {
    count, data
  };
}

class MembershipListPaths {
  static const JsonPath<int> count = JsonPath.internal(["count"], "/count");
  static const JsonPath<List<IMembership>> data = JsonPath.internal(["data"], "/data");
  static final Set<JsonPath> values = {
    count, data
  };
}


const MembershipListRef = MSchemaRef("sunny", "fact", "membershipList", "0.0.1", "ephemeral");

typedef _MembershipListConstructor = IMembershipList Function({   int? count, 
  List<IMembership>? data
 });
typedef _MembershipListFromJson = IMembershipList Function(dynamic any);