// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../facts_ext.dart';

import '../model/memory.dart';


abstract class IMemoryList
  implements MModel, MModelList<IMemory> {

  static late _MemoryListConstructor of;
  static late _MemoryListFromJson fromJson;

  /// Property getter and setter for count: 
  int? get count;
  set count(int? count);


  /// Property getter and setter for data: 
  List<IMemory>? get data;
  set data(List<IMemory>? data);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IMemoryList clone();

  @override
  Set<String> get mfields => MemoryListFields.values;

}

class MemoryListFields {
  static const count = "count";
  static const data = "data";
  static const Set<String> values = {
    count, data
  };
}

class MemoryListPaths {
  static const JsonPath<int> count = JsonPath.internal(["count"], "/count");
  static const JsonPath<List<IMemory>> data = JsonPath.internal(["data"], "/data");
  static final Set<JsonPath> values = {
    count, data
  };
}


const MemoryListRef = MSchemaRef("sunny", "fact", "memoryList", "0.0.1", "ephemeral");

typedef _MemoryListConstructor = IMemoryList Function({   int? count, 
  List<IMemory>? data
 });
typedef _MemoryListFromJson = IMemoryList Function(dynamic any);