// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';

import '../../reliveit/model/relive_it_contact.dart';
import '../model/fact.dart';
import '../model/task_fact_for_m_model.dart';
import 'package:sunny_sdk_core/sunny_sdk_core.dart';


abstract class IPayment implements IFact {
  /// Property getter and setter for amount: 
  double? get amount;
  

  /// Property getter and setter for reason: 
  String? get reason;
  

  /// Property getter and setter for notes: 
  String? get notes;
  

  /// Property getter and setter for paymentDate: 
  DateTime? get paymentDate;
  

  /// Property getter and setter for payee: 
  MKey? get payee;
  

  /// Property getter and setter for payor: 
  MKey? get payor;
  

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IPayment clone();

  @override
  Set<String> get mfields => PaymentFields.values;

}

class PaymentFields {
  
  static const creator = "creator";
  static const dateCreated = "dateCreated";
  static const assistedTask = "assistedTask";
  static const amount = "amount";
  static const reason = "reason";
  static const notes = "notes";
  static const paymentDate = "paymentDate";
  static const payee = "payee";
  static const payor = "payor";
  static const Set<String> values = {
    creator, dateCreated, assistedTask, amount, reason, notes, paymentDate, payee, payor
  };
}

class PaymentPaths {
  
  static const JsonPath<IReliveItContact> creator = JsonPath.internal(["creator"], "/creator");
  static const JsonPath<DateTime> dateCreated = JsonPath.internal(["dateCreated"], "/dateCreated");
  static const JsonPath<ITaskFactForMModel> assistedTask = JsonPath.internal(["assistedTask"], "/assistedTask");
  static const JsonPath<double> amount = JsonPath.internal(["amount"], "/amount");
  static const JsonPath<String> reason = JsonPath.internal(["reason"], "/reason");
  static const JsonPath<String> notes = JsonPath.internal(["notes"], "/notes");
  static const JsonPath<DateTime> paymentDate = JsonPath.internal(["paymentDate"], "/paymentDate");
  static const JsonPath<MKey> payee = JsonPath.internal(["payee"], "/payee");
  static const JsonPath<MKey> payor = JsonPath.internal(["payor"], "/payor");
  static final Set<JsonPath> values = {
    creator, dateCreated, assistedTask, amount, reason, notes, paymentDate, payee, payor
  };
}


const PaymentRef = MSchemaRef("sunny", "fact", "payment", "0.0.1", "mverse");