// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../facts_ext.dart';

import '../model/pet.dart';


abstract class IPetList
  implements MModel, MModelList<IPet> {

  static late _PetListConstructor of;
  static late _PetListFromJson fromJson;

  /// Property getter and setter for count: 
  int? get count;
  set count(int? count);


  /// Property getter and setter for data: 
  List<IPet>? get data;
  set data(List<IPet>? data);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IPetList clone();

  @override
  Set<String> get mfields => PetListFields.values;

}

class PetListFields {
  static const count = "count";
  static const data = "data";
  static const Set<String> values = {
    count, data
  };
}

class PetListPaths {
  static const JsonPath<int> count = JsonPath.internal(["count"], "/count");
  static const JsonPath<List<IPet>> data = JsonPath.internal(["data"], "/data");
  static final Set<JsonPath> values = {
    count, data
  };
}


const PetListRef = MSchemaRef("sunny", "fact", "petList", "0.0.1", "ephemeral");

typedef _PetListConstructor = IPetList Function({   int? count, 
  List<IPet>? data
 });
typedef _PetListFromJson = IPetList Function(dynamic any);