// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../facts_ext.dart';

import '../model/fact.dart';
import '../model/membership.dart';
import '../model/prep_school.dart';
import '../model/task_fact_for_m_model.dart';
import 'package:sunny_service_stubs/models/reliveit/model/relive_it_contact.dart';


abstract class IPrepSchoolStudent
  implements IMembership {

  static late _PrepSchoolStudentConstructor of;
  static late _PrepSchoolStudentFromJson fromJson;

  /// Property getter and setter for contactKey: 
  MKey? get contactKey;
  set contactKey(MKey? contactKey);


  /// Property getter and setter for school: 
  IPrepSchool? get school;
  set school(IPrepSchool? school);


  /// Property getter and setter for graduatingClass: 
  String? get graduatingClass;
  set graduatingClass(String? graduatingClass);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IPrepSchoolStudent clone();

  @override
  Set<String> get mfields => PrepSchoolStudentFields.values;

}

class PrepSchoolStudentFields {
  static const creator = "creator";
  static const dateCreated = "dateCreated";
  static const assistedTask = "assistedTask";
  static const isActive = "isActive";
  static const contactKey = "contactKey";
  static const school = "school";
  static const graduatingClass = "graduatingClass";
  static const Set<String> values = {
    creator, dateCreated, assistedTask, isActive, contactKey, school, graduatingClass
  };
}

class PrepSchoolStudentPaths {
  static const JsonPath<IReliveItContact> creator = JsonPath.internal(["creator"], "/creator");
  static const JsonPath<DateTime> dateCreated = JsonPath.internal(["dateCreated"], "/dateCreated");
  static const JsonPath<ITaskFactForMModel> assistedTask = JsonPath.internal(["assistedTask"], "/assistedTask");
  static const JsonPath<bool> isActive = JsonPath.internal(["isActive"], "/isActive");
  static const JsonPath<MKey> contactKey = JsonPath.internal(["contactKey"], "/contactKey");
  static const JsonPath<IPrepSchool> school = JsonPath.internal(["school"], "/school");
  static const JsonPath<String> graduatingClass = JsonPath.internal(["graduatingClass"], "/graduatingClass");
  static final Set<JsonPath> values = {
    creator, dateCreated, assistedTask, isActive, contactKey, school, graduatingClass
  };
}


const PrepSchoolStudentRef = MSchemaRef("sunny", "fact", "prepSchoolStudent", "0.0.1", "mverse");

typedef _PrepSchoolStudentConstructor = IPrepSchoolStudent Function({   IReliveItContact? creator, 
  required DateTime? dateCreated, 
  ITaskFactForMModel? assistedTask, 
  bool? isActive, 
  required MKey? contactKey, 
  required IPrepSchool? school, 
  String? graduatingClass
 });
typedef _PrepSchoolStudentFromJson = IPrepSchoolStudent Function(dynamic any);