// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';

import '../../reliveit/model/relive_it_contact.dart';
import '../model/fact.dart';
import '../model/task_fact_for_m_model.dart';
import 'package:sunny_sdk_core/sunny_sdk_core.dart';


abstract class IRemember implements IFact {
  /// Property getter and setter for contactKey: 
  MKey? get contactKey;
  

  /// Property getter and setter for rememberUntil: 
  DateTime? get rememberUntil;
  

  /// Property getter and setter for rememberTitle: 
  String? get rememberTitle;
  

  /// Property getter and setter for rememberDetails: 
  String? get rememberDetails;
  

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IRemember clone();

  @override
  Set<String> get mfields => RememberFields.values;

}

class RememberFields {
  
  static const creator = "creator";
  static const dateCreated = "dateCreated";
  static const assistedTask = "assistedTask";
  static const contactKey = "contactKey";
  static const rememberUntil = "rememberUntil";
  static const rememberTitle = "rememberTitle";
  static const rememberDetails = "rememberDetails";
  static const Set<String> values = {
    creator, dateCreated, assistedTask, contactKey, rememberUntil, rememberTitle, rememberDetails
  };
}

class RememberPaths {
  
  static const JsonPath<IReliveItContact> creator = JsonPath.internal(["creator"], "/creator");
  static const JsonPath<DateTime> dateCreated = JsonPath.internal(["dateCreated"], "/dateCreated");
  static const JsonPath<ITaskFactForMModel> assistedTask = JsonPath.internal(["assistedTask"], "/assistedTask");
  static const JsonPath<MKey> contactKey = JsonPath.internal(["contactKey"], "/contactKey");
  static const JsonPath<DateTime> rememberUntil = JsonPath.internal(["rememberUntil"], "/rememberUntil");
  static const JsonPath<String> rememberTitle = JsonPath.internal(["rememberTitle"], "/rememberTitle");
  static const JsonPath<String> rememberDetails = JsonPath.internal(["rememberDetails"], "/rememberDetails");
  static final Set<JsonPath> values = {
    creator, dateCreated, assistedTask, contactKey, rememberUntil, rememberTitle, rememberDetails
  };
}


const RememberRef = MSchemaRef("sunny", "fact", "remember", "0.0.1", "mverse");