// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../facts_ext.dart';



abstract class ITaskDueConfig
  implements MModel {

  static late _TaskDueConfigConstructor of;
  static late _TaskDueConfigFromJson fromJson;

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  ITaskDueConfig clone();

}


const TaskDueConfigRef = MSchemaRef("sunny", "fact", "taskDueConfig", "0.0.1", "ephemeral");

typedef _TaskDueConfigConstructor = ITaskDueConfig Function();
typedef _TaskDueConfigFromJson = ITaskDueConfig Function(dynamic any);