// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';

import '../../waypoints/model/image_content.dart';
import '../model/organization.dart';
import '../model/phase.dart';
import 'package:sunny_sdk_core/sunny_sdk_core.dart';


abstract class ITeam implements IOrganization {
  /// Property getter and setter for sport: 
  String? get sport;
  

  /// Property getter and setter for isInactive: 
  bool? get isInactive;
  

  /// Property getter and setter for coach: 
  MKey? get coach;
  

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  ITeam clone();

  @override
  Set<String> get mfields => TeamFields.values;

}

class TeamFields {
  
  static const name = "name";
  static const logo = "logo";
  static const phases = "phases";
  static const parent = "parent";
  static const sport = "sport";
  static const isInactive = "isInactive";
  static const coach = "coach";
  static const Set<String> values = {
    name, logo, phases, parent, sport, isInactive, coach
  };
}

class TeamPaths {
  
  static const JsonPath<String> name = JsonPath.internal(["name"], "/name");
  static const JsonPath<IImageContent> logo = JsonPath.internal(["logo"], "/logo");
  static const JsonPath<List<IPhase>> phases = JsonPath.internal(["phases"], "/phases");
  static const JsonPath<List<MKey>> parent = JsonPath.internal(["parent"], "/parent");
  static const JsonPath<String> sport = JsonPath.internal(["sport"], "/sport");
  static const JsonPath<bool> isInactive = JsonPath.internal(["isInactive"], "/isInactive");
  static const JsonPath<MKey> coach = JsonPath.internal(["coach"], "/coach");
  static final Set<JsonPath> values = {
    name, logo, phases, parent, sport, isInactive, coach
  };
}


const TeamRef = MSchemaRef("sunny", "fact", "team", "0.0.1", "mverse");