// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../facts_ext.dart';

import '../model/fact.dart';
import '../model/task_fact_for_m_model.dart';
import 'package:sunny_sdk_core/sunny_sdk_core.dart';
import 'package:sunny_service_stubs/models/reliveit/model/relive_it_contact.dart';


abstract class ITrait
  implements IFact {

  static late _TraitConstructor of;
  static late _TraitFromJson fromJson;

  /// Property getter and setter for contactKey: 
  MKey? get contactKey;
  set contactKey(MKey? contactKey);


  /// Property getter and setter for traitType: 
  String? get traitType;
  set traitType(String? traitType);


  /// Property getter and setter for traitTitle: 
  String? get traitTitle;
  set traitTitle(String? traitTitle);


  /// Property getter and setter for traitDescription: 
  String? get traitDescription;
  set traitDescription(String? traitDescription);


  /// Property getter and setter for emotes: 
  List<String>? get emotes;
  set emotes(List<String>? emotes);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  ITrait clone();

  @override
  Set<String> get mfields => TraitFields.values;

}

class TraitFields {
  static const creator = "creator";
  static const dateCreated = "dateCreated";
  static const assistedTask = "assistedTask";
  static const contactKey = "contactKey";
  static const traitType = "traitType";
  static const traitTitle = "traitTitle";
  static const traitDescription = "traitDescription";
  static const emotes = "emotes";
  static const Set<String> values = {
    creator, dateCreated, assistedTask, contactKey, traitType, traitTitle, traitDescription, emotes
  };
}

class TraitPaths {
  static const JsonPath<IReliveItContact> creator = JsonPath.internal(["creator"], "/creator");
  static const JsonPath<DateTime> dateCreated = JsonPath.internal(["dateCreated"], "/dateCreated");
  static const JsonPath<ITaskFactForMModel> assistedTask = JsonPath.internal(["assistedTask"], "/assistedTask");
  static const JsonPath<MKey> contactKey = JsonPath.internal(["contactKey"], "/contactKey");
  static const JsonPath<String> traitType = JsonPath.internal(["traitType"], "/traitType");
  static const JsonPath<String> traitTitle = JsonPath.internal(["traitTitle"], "/traitTitle");
  static const JsonPath<String> traitDescription = JsonPath.internal(["traitDescription"], "/traitDescription");
  static const JsonPath<List<String>> emotes = JsonPath.internal(["emotes"], "/emotes");
  static final Set<JsonPath> values = {
    creator, dateCreated, assistedTask, contactKey, traitType, traitTitle, traitDescription, emotes
  };
}


const TraitRef = MSchemaRef("sunny", "fact", "trait", "0.0.1", "mverse");

typedef _TraitConstructor = ITrait Function({   IReliveItContact? creator, 
  required DateTime? dateCreated, 
  ITaskFactForMModel? assistedTask, 
  required MKey? contactKey, 
  String? traitType, 
  required String? traitTitle, 
  required String? traitDescription, 
  List<String>? emotes
 });
typedef _TraitFromJson = ITrait Function(dynamic any);