// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../facts_ext.dart';

import '../model/trait.dart';


abstract class ITraitList
  implements MModel, MModelList<ITrait> {

  static late _TraitListConstructor of;
  static late _TraitListFromJson fromJson;

  /// Property getter and setter for count: 
  int? get count;
  set count(int? count);


  /// Property getter and setter for data: 
  List<ITrait>? get data;
  set data(List<ITrait>? data);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  ITraitList clone();

  @override
  Set<String> get mfields => TraitListFields.values;

}

class TraitListFields {
  static const count = "count";
  static const data = "data";
  static const Set<String> values = {
    count, data
  };
}

class TraitListPaths {
  static const JsonPath<int> count = JsonPath.internal(["count"], "/count");
  static const JsonPath<List<ITrait>> data = JsonPath.internal(["data"], "/data");
  static final Set<JsonPath> values = {
    count, data
  };
}


const TraitListRef = MSchemaRef("sunny", "fact", "traitList", "0.0.1", "ephemeral");

typedef _TraitListConstructor = ITraitList Function({   int? count, 
  List<ITrait>? data
 });
typedef _TraitListFromJson = ITraitList Function(dynamic any);