// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../sunny_ext.dart';



abstract class IAccountSettings
  implements MModel {

  static late _AccountSettingsConstructor of;
  static late _AccountSettingsFromJson fromJson;

  /// Property getter and setter for name: 
  String? get name;
  set name(String? name);


  /// Property getter and setter for value: 
  String? get value;
  set value(String? value);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IAccountSettings clone();

  @override
  Set<String> get mfields => AccountSettingsFields.values;

}

class AccountSettingsFields {
  static const name = "name";
  static const value = "value";
  static const Set<String> values = {
    name, value
  };
}

class AccountSettingsPaths {
  static const JsonPath<String> name = JsonPath.internal(["name"], "/name");
  static const JsonPath<String> value = JsonPath.internal(["value"], "/value");
  static final Set<JsonPath> values = {
    name, value
  };
}


const AccountSettingsRef = MSchemaRef("mverse", "sunny", "accountSettings", "0.0.1", "ephemeral");

typedef _AccountSettingsConstructor = IAccountSettings Function({   String? name, 
  String? value
 });
typedef _AccountSettingsFromJson = IAccountSettings Function(dynamic any);