// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';



abstract class IAppInfo implements MModel {
  /// Property getter and setter for forceUpgradePrior: 
  String? get forceUpgradePrior;
  

  /// Property getter and setter for warnUpgradePrior: 
  String? get warnUpgradePrior;
  

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IAppInfo clone();

  @override
  Set<String> get mfields => AppInfoFields.values;

}

class AppInfoFields {
  
  static const forceUpgradePrior = "forceUpgradePrior";
  static const warnUpgradePrior = "warnUpgradePrior";
  static const Set<String> values = {
    forceUpgradePrior, warnUpgradePrior
  };
}

class AppInfoPaths {
  
  static const JsonPath<String> forceUpgradePrior = JsonPath.internal(["forceUpgradePrior"], "/forceUpgradePrior");
  static const JsonPath<String> warnUpgradePrior = JsonPath.internal(["warnUpgradePrior"], "/warnUpgradePrior");
  static final Set<JsonPath> values = {
    forceUpgradePrior, warnUpgradePrior
  };
}


const AppInfoRef = MSchemaRef("mverse", "sunny", "appInfo", "0.0.1", "ephemeral");