// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';



abstract class IChangePasswordRequest implements MModel {
  /// Property getter and setter for oldPassword: 
  String? get oldPassword;
  

  /// Property getter and setter for newPassword: 
  String? get newPassword;
  

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IChangePasswordRequest clone();

  @override
  Set<String> get mfields => ChangePasswordRequestFields.values;

}

class ChangePasswordRequestFields {
  
  static const oldPassword = "oldPassword";
  static const newPassword = "newPassword";
  static const Set<String> values = {
    oldPassword, newPassword
  };
}

class ChangePasswordRequestPaths {
  
  static const JsonPath<String> oldPassword = JsonPath.internal(["oldPassword"], "/oldPassword");
  static const JsonPath<String> newPassword = JsonPath.internal(["newPassword"], "/newPassword");
  static final Set<JsonPath> values = {
    oldPassword, newPassword
  };
}


const ChangePasswordRequestRef = MSchemaRef("mverse", "sunny", "changePasswordRequest", "0.0.1", "ephemeral");