// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, non_constant_identifier_names, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../sunny_ext.dart';



abstract class IContactEmail
  implements MModel {

  static late _ContactEmailConstructor of;
  static late _ContactEmailFromJson fromJson;

  /// Property getter and setter for type: 
  String? get type;
  set type(String? type);


  /// Property getter and setter for email: 
  String? get email;
  set email(String? email);


  /// Property getter and setter for sortOrder: 
  int? get sortOrder;
  set sortOrder(int? sortOrder);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IContactEmail clone();

  @override
  Set<String> get mfields => ContactEmailFields.values;

}

class ContactEmailFields {
  static const type = "type";
  static const email = "email";
  static const sortOrder = "sortOrder";
  static const Set<String> values = {
    type, email, sortOrder
  };
}

class ContactEmailPaths {
  static const JsonPath<String> type = JsonPath.internal(["type"], "/type");
  static const JsonPath<String> email = JsonPath.internal(["email"], "/email");
  static const JsonPath<int> sortOrder = JsonPath.internal(["sortOrder"], "/sortOrder");
  static final Set<JsonPath> values = {
    type, email, sortOrder
  };
}


const ContactEmailRef = MSchemaRef("mverse", "sunny", "contactEmail", "0.0.1", "ephemeral");

typedef _ContactEmailConstructor = IContactEmail Function({   String? type, 
  required String? email, 
  int? sortOrder
 });
typedef _ContactEmailFromJson = IContactEmail Function(dynamic any);