// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';



abstract class IImportBundleRequest implements MModel {
  /// Property getter and setter for groupIds: 
  List<String>? get groupIds;
  

  /// Property getter and setter for contactIds: 
  List<String>? get contactIds;
  

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IImportBundleRequest clone();

  @override
  Set<String> get mfields => ImportBundleRequestFields.values;

}

class ImportBundleRequestFields {
  
  static const groupIds = "groupIds";
  static const contactIds = "contactIds";
  static const Set<String> values = {
    groupIds, contactIds
  };
}

class ImportBundleRequestPaths {
  
  static const JsonPath<List<String>> groupIds = JsonPath.internal(["groupIds"], "/groupIds");
  static const JsonPath<List<String>> contactIds = JsonPath.internal(["contactIds"], "/contactIds");
  static final Set<JsonPath> values = {
    groupIds, contactIds
  };
}


const ImportBundleRequestRef = MSchemaRef("mverse", "sunny", "importBundleRequest", "0.0.1", "ephemeral");