// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';



abstract class IProcessResetPasswordRequest implements MModel {
  /// Property getter and setter for password: 
  String? get password;
  

  /// Property getter and setter for token: 
  String? get token;
  

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IProcessResetPasswordRequest clone();

  @override
  Set<String> get mfields => ProcessResetPasswordRequestFields.values;

}

class ProcessResetPasswordRequestFields {
  
  static const password = "password";
  static const token = "token";
  static const Set<String> values = {
    password, token
  };
}

class ProcessResetPasswordRequestPaths {
  
  static const JsonPath<String> password = JsonPath.internal(["password"], "/password");
  static const JsonPath<String> token = JsonPath.internal(["token"], "/token");
  static final Set<JsonPath> values = {
    password, token
  };
}


const ProcessResetPasswordRequestRef = MSchemaRef("mverse", "sunny", "processResetPasswordRequest", "0.0.1", "ephemeral");