// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';



abstract class IRefreshTokenRequest implements MModel {
  /// Property getter and setter for refreshToken: 
  String? get refreshToken;
  set refreshToken(String? refreshToken);

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  IRefreshTokenRequest clone();

  @override
  Set<String> get mfields => RefreshTokenRequestFields.values;

}

class RefreshTokenRequestFields {
  
  static const refreshToken = "refreshToken";
  static const Set<String> values = {
    refreshToken
  };
}

class RefreshTokenRequestPaths {
  
  static const JsonPath<String> refreshToken = JsonPath.internal(["refreshToken"], "/refreshToken");
  static final Set<JsonPath> values = {
    refreshToken
  };
}


const RefreshTokenRequestRef = MSchemaRef("mverse", "sunny", "refreshTokenRequest", "0.0.1", "ephemeral");