// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';
import '../sunny_ext.dart';



abstract class ISource
  implements MModel {

  static late _SourceConstructor of;
  static late _SourceFromJson fromJson;

  /// Property getter and setter for id: 
  String? get id;
  set id(String? id);


  /// Property getter and setter for type: 
  String? get type;
  set type(String? type);


  /// Property getter and setter for identifier: 
  String? get identifier;
  set identifier(String? identifier);


  /// Property getter and setter for name: 
  String? get name;
  set name(String? name);


  /// Property getter and setter for credentials: 
  dynamic? get credentials;
  set credentials(dynamic? credentials);


  /// Property getter and setter for credentialsValid: 
  bool? get credentialsValid;
  set credentialsValid(bool? credentialsValid);


  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  ISource clone();

  @override
  Set<String> get mfields => SourceFields.values;

}

class SourceFields {
  static const id = "id";
  static const type = "type";
  static const identifier = "identifier";
  static const name = "name";
  static const credentials = "credentials";
  static const credentialsValid = "credentialsValid";
  static const Set<String> values = {
    id, type, identifier, name, credentials, credentialsValid
  };
}

class SourcePaths {
  static const JsonPath<String> id = JsonPath.internal(["id"], "/id");
  static const JsonPath<String> type = JsonPath.internal(["type"], "/type");
  static const JsonPath<String> identifier = JsonPath.internal(["identifier"], "/identifier");
  static const JsonPath<String> name = JsonPath.internal(["name"], "/name");
  static const JsonPath<dynamic> credentials = JsonPath.internal(["credentials"], "/credentials");
  static const JsonPath<bool> credentialsValid = JsonPath.internal(["credentialsValid"], "/credentialsValid");
  static final Set<JsonPath> values = {
    id, type, identifier, name, credentials, credentialsValid
  };
}


const SourceRef = MSchemaRef("mverse", "sunny", "source", "0.0.1", "ephemeral");

typedef _SourceConstructor = ISource Function({   String? id, 
  String? type, 
  String? identifier, 
  String? name, 
  dynamic? credentials, 
  bool? credentialsValid
 });
typedef _SourceFromJson = ISource Function(dynamic any);