// ignore_for_file: duplicate_import, unused_import, directives_ordering, unnecessary_null_comparison, unnecessary_non_null_assertion

// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:sunny_sdk_core/model_exports.dart';



abstract class ITag implements MModel {
  /// Property getter and setter for name: 
  String? get name;
  

  /// Property getter and setter for value: 
  String? get value;
  

  @override
  String toString();
  dynamic toJson();

  @override
  operator [](key);

  @override
  operator []=(String key, value);

  @override
  void takeFrom(source);

  @override
  void takeFromMap(Map<String, dynamic>? from, {bool copyEntries = true});

  @override
  ITag clone();

  @override
  Set<String> get mfields => TagFields.values;

}

class TagFields {
  
  static const name = "name";
  static const value = "value";
  static const Set<String> values = {
    name, value
  };
}

class TagPaths {
  
  static const JsonPath<String> name = JsonPath.internal(["name"], "/name");
  static const JsonPath<String> value = JsonPath.internal(["value"], "/value");
  static final Set<JsonPath> values = {
    name, value
  };
}


const TagRef = MSchemaRef("mverse", "sunny", "tag", "0.0.1", "ephemeral");